#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDM.AdcGateway
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AdcSync_Test")]
	public partial class PartyCrossMapDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public PartyCrossMapDataContext() : 
				base(global::MDM.AdcGateway.Properties.Settings.Default.AdcSync_TestConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PartyCrossMapDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PartyCrossMapDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PartyCrossMapDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PartyCrossMapDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<PartyCrossMap> PartyCrossMaps
		{
			get
			{
				return this.GetTable<PartyCrossMap>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PartyCrossMap")]
	public partial class PartyCrossMap
	{
		
		private int _MapId1;
		
		private string _System1;
		
		private string _MapValue1;
		
		private int _MapId2;
		
		private string _System2;
		
		private string _MapValue2;
		
		private string _Commodity;
		
		public PartyCrossMap()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MapId1", DbType="Int NOT NULL")]
		public int MapId1
		{
			get
			{
				return this._MapId1;
			}
			set
			{
				if ((this._MapId1 != value))
				{
					this._MapId1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_System1", DbType="VarChar(50)")]
		public string System1
		{
			get
			{
				return this._System1;
			}
			set
			{
				if ((this._System1 != value))
				{
					this._System1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MapValue1", DbType="VarChar(200)")]
		public string MapValue1
		{
			get
			{
				return this._MapValue1;
			}
			set
			{
				if ((this._MapValue1 != value))
				{
					this._MapValue1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MapId2", DbType="Int NOT NULL")]
		public int MapId2
		{
			get
			{
				return this._MapId2;
			}
			set
			{
				if ((this._MapId2 != value))
				{
					this._MapId2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_System2", DbType="VarChar(50)")]
		public string System2
		{
			get
			{
				return this._System2;
			}
			set
			{
				if ((this._System2 != value))
				{
					this._System2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MapValue2", DbType="VarChar(200)")]
		public string MapValue2
		{
			get
			{
				return this._MapValue2;
			}
			set
			{
				if ((this._MapValue2 != value))
				{
					this._MapValue2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Commodity", DbType="VarChar(50)")]
		public string Commodity
		{
			get
			{
				return this._Commodity;
			}
			set
			{
				if ((this._Commodity != value))
				{
					this._Commodity = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
